### ISSUE TITLE
Wireless Crafting Grid recipe mod transfer not working

### ISSUE THREAD

**Issue by Moj-FPS** [refinedmods/refinedstorage-quartz-arsenal#12]
### Describe the bug

"+" button to add recipe from JEI to wireless crafting grid is missing

### How can we reproduce this bug or crash?

1. Open wireless crafting grid
2. Select recipe in JEI
3. No option to add recipe to crafting grid 

### What Minecraft version is this happening on?

Minecraft 1.21

### What NeoForge or Fabric version is this happening on?

NeoForge 21.1.81

### What version is this happening on?

0.1.0

### Relevant log output

```shell
N/A
```

**Comment by Agent40infinity** [comment]
Additional notes: 
Isn’t just for wireless crafting grid, all grids don’t have the prompt to “move items” on JEI. 

Expected Outcome: 
Non recipe matching UI will fade out “Move Items” showing that you’re unable to perform the action in such functional block while allowing you to auto fill in matching UI.

Current Result:
For all grids, JEI doesn’t display the button at all let alone let you interact with it. Feels like JEI doesn’t recognise that the block UIs exist.

Hope this helps narrow the issue down

**Comment by Moj-FPS** [comment]
Do you have the JEI addon installed? The regular crafting grid works fine
for me.

**Comment by RC-AidenNathan** [comment]
Yep that was it, cheers.

**Comment by raoulvdberge** [comment]
Fixed for REI in https://github.com/refinedmods/refinedstorage-rei-integration/commit/4fa209149af22614802382b95bdcf2b3c82437ad

**Comment by raoulvdberge** [comment]
Fixed for JEI in https://github.com/refinedmods/refinedstorage-jei-integration/commit/5474db36998cc38f6c8d265cc4c8a546f56bc6ee

**Comment by raoulvdberge** [comment]
Fixed for EMI in https://github.com/refinedmods/refinedstorage-emi-integration/commit/4afe322ac5a36aa6879e1f84ec126be15935d32e
